# Generated by Django 5.0.1 on 2024-12-29 08:33

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('default_layout', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('apartment', 'Apartment Building'), ('villa', 'Villa'), ('rooms', 'Normal Rooms'), ('bungalow', 'Bungalow')], max_length=20)),
                ('total_floors', models.PositiveIntegerField(default=1, help_text='Number of floors including ground floor', validators=[django.core.validators.MinValueValidator(1)])),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('address', models.TextField()),
                ('boundary', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('total_area', models.DecimalField(decimal_places=2, help_text='Total area in square meters', max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='properties/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Properties',
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('total_units', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('layout_type', models.CharField(choices=[('rectangular', 'Rectangular'), ('l_shaped', 'L-Shaped'), ('u_shaped', 'U-Shaped'), ('custom', 'Custom')], default='rectangular', max_length=20)),
                ('layout_creation_method', models.CharField(choices=[('auto', 'Auto-Generated'), ('manual', 'Manually Drawn'), ('upload', 'Uploaded Floor Plan'), ('template', 'From Template')], default='auto', help_text='Method used to create the floor layout', max_length=20)),
                ('layout_data', models.JSONField(blank=True, help_text='Stores layout configuration, drawing data, or image processing results', null=True)),
                ('area', models.DecimalField(decimal_places=2, help_text='Floor area in square meters', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='properties.property')),
            ],
            options={
                'ordering': ['floor_number'],
                'unique_together': {('property', 'floor_number')},
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.CharField(max_length=50)),
                ('location', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('area', models.DecimalField(decimal_places=2, help_text='Area in square meters', max_digits=8)),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('biannual', 'Bi-Annual'), ('annual', 'Annual'), ('custom', 'Custom')], default='monthly', max_length=20)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('maintenance', 'Under Maintenance'), ('reserved', 'Reserved')], default='available', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='properties.floor')),
                ('unit_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='properties.unittype')),
            ],
            options={
                'ordering': ['unit_number'],
                'unique_together': {('floor', 'unit_number')},
            },
        ),
    ]
