# Generated by Django 5.0.1 on 2024-12-29 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('reported_date', models.DateTimeField(auto_now_add=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('emergency', 'Emergency')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('assigned_to', models.CharField(blank=True, max_length=255, null=True)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Unit Maintenance',
                'verbose_name_plural': 'Unit Maintenance Issues',
                'ordering': ['-reported_date'],
            },
        ),
        migrations.CreateModel(
            name='UnitUtility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utility_type', models.CharField(max_length=50)),
                ('included_in_rent', models.BooleanField(default=False)),
                ('meter_number', models.CharField(blank=True, max_length=50, null=True)),
                ('cost_allocation', models.CharField(choices=[('landlord', 'Landlord'), ('tenant', 'Tenant')], default='tenant', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Unit Utility',
                'verbose_name_plural': 'Unit Utilities',
                'ordering': ['utility_type'],
            },
        ),
        migrations.RemoveField(
            model_name='unit',
            name='area',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='location',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='payment_frequency',
        ),
        migrations.AddField(
            model_name='unit',
            name='amenities',
            field=models.JSONField(default=dict, help_text='Unit-specific amenities and features'),
        ),
    ]
