# Generated by Django 5.0.1 on 2024-12-29 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_unitmaintenance_unitutility_remove_unit_area_and_more'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='current_tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_unit', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='unit',
            name='layout_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='max_occupants',
            field=models.PositiveIntegerField(default=1, help_text='Maximum number of allowed occupants'),
        ),
        migrations.AddField(
            model_name='unit',
            name='occupancy_history',
            field=models.ManyToManyField(blank=True, related_name='unit_history', to='tenants.tenantoccupancy'),
        ),
        migrations.AddField(
            model_name='unit',
            name='size',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Size in square meters', max_digits=10),
        ),
        migrations.AlterField(
            model_name='unit',
            name='rent_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit_type',
            field=models.CharField(default='standard', max_length=50),
        ),
        migrations.AddField(
            model_name='unitmaintenance',
            name='reported_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='unitmaintenance',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_issues', to='properties.unit'),
        ),
        migrations.AddField(
            model_name='unitutility',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilities', to='properties.unit'),
        ),
    ]
